src/lib/components/Course/components/Lesson/functions.ts, src/lib/components/Question/CheckboxQuestion/index.svelte, src/lib/components/Question/Grade.svelte, src/lib/components/Question/RadioQuestion/index.svelte, src/lib/components/Question/TextareaQuestion/index.svelte, src/routes/courses/[id]/lessons/[...lessonParams]/+page.svelte, src/routes/courses/[id]/submissions/+page.svelte
Fixes https://github.com/rotimi-best/classroomio/issues/7
=> fix: grading input disappears on change #7

src/lib/components/WelcomeModal/WelcomeModal.svelte
Fixes: https://github.com/rotimi-best/classroomio/issues/24
=> feat: prompt user to new course modal

apps/dashboard/src/lib/components/TextEditor/index.svelte, apps/dashboard/src/routes/lms/community/ask/+page.svelte, apps/dashboard/src/routes/org/[slug]/community/ask/+page.svelte
Fixes https://github.com/rotimi-best/classroomio/issues/33
https://github.com/rotimi-best/classroomio/assets/31730715/52a73135-6b10-467e-8116-79c9b5ca84da
- Go to community page
- Click on Ask
- Toggle darkmode and light mode
=> fix: title and description on community post to support dark mode 

apps/docs/pages/_meta.json, apps/docs/pages/about.mdx, apps/docs/pages/audience.mdx, apps/docs/pages/community.mdx, apps/docs/pages/contributorguides/_meta.json, apps/docs/pages/contributorguides/design.mdx, apps/docs/pages/contributorguides/devs.mdx, apps/docs/pages/contributorguides/localstudentdashboard.mdx, apps/docs/pages/course.mdx, apps/docs/pages/getting-started.mdx, apps/docs/pages/howtoguides/_meta.json, apps/docs/pages/howtoguides/createfirstcourse.mdx, apps/docs/pages/howtoguides/customizeorganization.mdx, apps/docs/pages/howtoguides/inviteteammember.mdx, apps/docs/pages/index.mdx, apps/docs/pages/organization.mdx, apps/docs/pages/quickstart/_meta.json, apps/docs/pages/quickstart/onboarding.mdx, apps/docs/pages/quickstart/selfhosting.mdx, apps/docs/pages/quickstart/signup.mdx, apps/docs/pages/studentdashboard.mdx, apps/docs/pages/what-is-classroomio.mdx, apps/docs/theme.config.tsx
Setup the documentation structure
Fixes #30
Watch demo: https://jam.dev/c/41887f78-0da9-4549-bc59-31b1f5bde3a4
- Read the docs
=> feat: setup documentation structure

apps/docs/pages/howtoguides/_meta.json, apps/docs/pages/howtoguides/certificates.mdx, apps/docs/pages/howtoguides/courselandingpage.mdx, apps/docs/pages/howtoguides/createexercise.mdx, apps/docs/pages/howtoguides/createfirstcourse.mdx, apps/docs/pages/howtoguides/gradeexercise.mdx, apps/docs/pages/howtoguides/invitestudents.mdx, apps/docs/pages/howtoguides/setupprofile.mdx, apps/docs/pages/howtoguides/takeattendance.mdx
=> docs: add more how to guides

.github/workflows/assign-issues.yml, .github/workflows/auto-comment-issues.yml
This PR automates adding comments to opened issues and auto-assigns issues to contributors by adding ".take"
Fixes #41 
- Create a new issue and the bot adds a comment to it
=> feat: automate issues

apps/classroomio-com/README.md, apps/classroomio-com/src/app.html, apps/classroomio-com/src/lib/Hero/Hero.svelte, apps/dashboard/README.md, apps/dashboard/src/app.html
- To test this, you must run `npm run dev`
=> fix: Corrected "Stuffs" to "Stuff" on the landing page

apps/dashboard/src/lib/components/Org/AddOrgModal/AddOrgModal.svelte
This PR fixed issue #45 
- [ √] Bug fix (non-breaking change which fixes an issue)
Video showing the changes[ here](https://drive.google.com/file/d/1sVJrSML2zvBlYwy8Gtuyk9uKfLEzi5O8/view?usp=sharing)
=> fix: create-org-bug

apps/dashboard/src/lib/components/Course/components/Lesson/Exercises/index.svelte
According to the Issue #87: Exercise Date Discrepancy, There was a discrepancy where the exercise dates created were not corresponding with the created date as expected, and this could cause confusion for others in the future.
It will show Today/Tomorrow/Yesterday or the actual date.
The dates assigned to the exercises now align with the dates on which they were originally created.
Log in to your dashboard by clicking and entering your credentials in the email and password fields.
Navigate to the "Courses" feature on your dashboard.
Choose a specific course from your created list.
Select the "Lessons" feature.
Navigate to the exercise section
Observe the exercise date displayed.
=> fix: Exercise dates have been fixed

apps/dashboard/src/lib/components/Org/Settings/TeamMembers.svelte, apps/dashboard/src/routes/org/[slug]/community/[slug]/+page.svelte, apps/dashboard/src/routes/org/[slug]/community/ask/+page.svelte
This PR Fixes the Duplicate Response Messages on certain actions
Fixes #90
- To test this, you must run `npm run dev` or `pnpm dev`
=> fix: Corrected Duplicate Response Messages

apps/classroomio-com/src/lib/Faq/Faq.svelte
Improves the Readability of the answers in the FAQ section of the landing page
these images hows the difference in the readability after improving the font size
- checked it from my local host
=> fix: Improved font size for the answers in the FAQ section of the landing page

apps/dashboard/src/routes/signup/+page.svelte
Fixes https://github.com/rotimi-best/classroomio/issues/99
- Test A
- Test B
=> feat: Verify if user's email is disposable on sign up

apps/dashboard/src/lib/components/Courses/components/Card/index.svelte, apps/dashboard/src/lib/components/Courses/index.svelte, package.json
This PR adds a context menu to the course cards on the "Courses" page when the card is right-clicked. The options added to the menu are:
- Clone
- Share
- Invite
- Delete
Fixes #80 
- On the dashboard, navigate to the "Course" page.
- On the "Course" page, right-click on any course, and you should see a context menu with options to clone the course, share the course, delete the course, and invite people to the course.
- Clicking on any of the options would bring up a browser alert.
- Note the functionality for the options of the menu is not yet implemented.
=> feat: Add course card context menu on course page

apps/dashboard/src/routes/courses/[id]/people/+page.svelte
Fixes #114 
- create a course
- click on the people menu option
- look at the email of the people
=> feat(page): hide email of people in a course

apps/classroomio-com/src/lib/Pricing/Pricing.svelte
Correct the pricing section of the home page, under the Teams section. the first item there is Everything in Teams which should  be Everything in Pro?
- Test A
- Test B
=> fix: Correct feature Item in pricing list. Closes #125

apps/dashboard/src/lib/components/OrgSelector/OrgSelector.svelte
Fixed the caret icon on sidebar Component which is used to change org.
Fixes #119 
Change can be seen on sidebar on dashboard route
=> fix: Home page on the teacher's view 

apps/dashboard/.env.example, apps/dashboard/README.md, apps/dashboard/src/lib/utils/functions/supabase.ts, apps/dashboard/src/lib/utils/types/config.ts
Removes the unused env variable `PUBLIC_SUPABASE_BUCKET_URL`
- Test A
- Test B
=> refactor: remove unused supabase storage path

apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte, apps/dashboard/src/routes/+page.svelte
Fixes the issue of a student unable to submit an exercise
- Login as a student
- Visit any exercise
- Try hitting start
- You should see the first question
=> fix: student unable to view exercise

apps/dashboard/package.json, apps/dashboard/src/lib/components/Course/components/Settings/index.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/HeaderForm.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/index.svelte, apps/dashboard/src/lib/components/CourseLandingPage/index.svelte, apps/dashboard/src/lib/utils/functions/showAppsSideBar.js, pnpm-lock.yaml
This PR fixes the issue with the "replace button" in the course landing page not working. I imported the upload widget component in course landing page file and placed it in a conditional render based on the store value of the widget itself. I edited the function of the replace button so what it does is set the value of the widget store which will alter the condition and affect the rendering of the upload component.
This fixes issue #46 
https://github.com/rotimi-best/classroomio/assets/88969825/94b60b7b-6c68-42ad-948f-aef1b729735a
- Test A
- Test B
=> fix: replace button not working on landing page editor

README.md
Adds a made with supabase badge
- [*] New feature (non-breaking change which adds functionality)
=> feat: add made with supabase

apps/dashboard/src/lib/components/Apps/components/Poll/index.svelte, apps/dashboard/src/lib/components/Apps/components/Poll/utils.ts, apps/dashboard/src/lib/components/Apps/index.svelte, apps/dashboard/src/lib/components/Apps/store.ts, apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte, apps/dashboard/src/lib/components/Course/components/Lesson/AddLessonModal.svelte, apps/dashboard/src/lib/components/Course/components/Navigation/NavExpandable.svelte, apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte, apps/dashboard/src/lib/components/Course/components/Navigation/store.js, apps/dashboard/src/lib/components/CourseContainer/index.svelte, apps/dashboard/src/lib/components/Courses/index.svelte, apps/dashboard/src/lib/components/Navigation/app.svelte, apps/dashboard/src/lib/components/Navigation/lms.svelte, apps/dashboard/src/lib/components/TextEditor/index.svelte, apps/dashboard/src/lib/utils/store/app.js, apps/dashboard/src/lib/utils/store/app.ts, apps/dashboard/src/routes/+error.svelte, apps/dashboard/src/routes/+layout.svelte, apps/dashboard/src/routes/404/+page.svelte, apps/dashboard/src/routes/courses/[id]/+layout.svelte, apps/dashboard/src/routes/courses/[id]/attendance/+page.svelte, apps/dashboard/src/routes/courses/[id]/certificates/+page.svelte, apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte, apps/dashboard/src/routes/courses/[id]/lessons/[...lessonParams]/+page.svelte, apps/dashboard/src/routes/courses/[id]/marks/+page.svelte, apps/dashboard/src/routes/courses/[id]/people/+page.svelte, apps/dashboard/src/routes/courses/[id]/settings/+page.svelte, apps/dashboard/src/routes/org/[slug]/+page.svelte
Fixes #143 
- To test this feature, you go to the course page and click on the "+" icon on the sidebar on the left next to the chevron icon facing down and the addLessonModal pops up as expected.
=> feat: add extra button to control addLessonModal to ease user experience 

CONTRIBUTING.md
Updates link that redirects to Gitpod in Contributing.md
=> docs: updates link that redirects to Gitpod in Contributing.md

README.md, apps/classroomio-com/README.md, apps/classroomio-com/src/app.html, apps/dashboard/README.md, apps/docs/README.md
=> docs: update tagline in github

apps/docs/pages/howtoguides/create-first-course.mdx, apps/docs/pages/quickstart/signup.mdx
=> docs: spelling corrections

apps/dashboard/src/lib/components/Course/components/Lesson/AddLessonModal.svelte, apps/dashboard/src/lib/components/PageNav/index.svelte, apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
This reduces the height of the lesson card on /lessons route
- Test A
- Test B
=> chore: improve style of lesson card

apps/dashboard/src/lib/components/Course/components/Settings/index.svelte
=> chore: generate slug if none when course is published

apps/dashboard/src/lib/components/CourseLandingPage/index.svelte, apps/dashboard/src/lib/components/Org/Settings/Domains.svelte, apps/dashboard/src/lib/utils/functions/validator.js
This PR makes sure that users can only create an orgSiteName with a minimum of 5 characters
- Go through onboarding
- Configure domain in organisation settings
=> feat: enforce rule of org site name with min of 5 chars

apps/dashboard/package.json, apps/dashboard/src/defer/sendEmail.ts, apps/dashboard/src/lib/components/Course/components/NewsFeed/NewsFeedCard.svelte, apps/dashboard/src/lib/utils/services/newsfeed/index.ts, apps/dashboard/src/lib/utils/types/feed.ts, apps/dashboard/src/routes/api/email/course/exercise_submission_update/+server.js, apps/dashboard/src/routes/api/email/course/newsfeed/+server.ts, apps/dashboard/src/routes/api/email/course/student_prove_payment/+server.js, apps/dashboard/src/routes/api/email/course/student_welcome/+server.js, apps/dashboard/src/routes/api/email/course/submission_update/+server.js, apps/dashboard/src/routes/api/email/course/teacher_student_buycourse/+server.js, apps/dashboard/src/routes/api/email/course/teacher_student_joined/+server.js, apps/dashboard/src/routes/api/email/course/teacher_welcome/+server.js, apps/dashboard/src/routes/api/email/invite/+server.js, apps/dashboard/src/routes/api/email/welcome/+server.js, apps/dashboard/src/routes/courses/[id]/+page.svelte, apps/dashboard/svelte.config.js, apps/dashboard/tsconfig.json, pnpm-lock.yaml
=> feat: move all email to defer queue

.github/workflows/deploy-supabase-stg-on-push.yml
Always keep supabase staging schema in sync with prod on merge to main
- Test A
- Test B
=> ci: add supabase staging deployment

apps/dashboard/src/lib/components/Buttons/Logout/index.svelte
Fixes this error on sentry with console error
- Test A
- Test B
=> chore: fix logout console error

apps/classroomio-com/src/lib/Hero/Hero.svelte, apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte
=> chore: lesson card buggy behavior and refactor hero

.github/workflows/deploy-backend-on-push.yml, apps/backend/package.json, apps/backend/server.js, apps/backend/src/routes/uploadVideo.js
Fixes #190 
- Deploy to backend and test
=> feat: video upload - disable muse upload + upgrade server

.github/workflows/deploy-backend-on-push.yml, apps/backend/package.json, apps/backend/src/routes/uploadVideo.js, apps/dashboard/src/lib/components/Course/components/Lesson/Materials/Video/LocalVideo.svelte, pnpm-lock.yaml
Fixes #190
In this PR,
1. I experimented with a new simpler approach of uploading videos through the S3 client package to cloudflare in chunks which makes upload much faster.
2. I increased the timeout for that endpoint to 15 minutes for larger videos to prevent express from crashing
I tried uploading a 400+ mb video and it took less than 4 minutes
This is also a good resource that helped me understand how to upload a video directly to cloudflare from the browser: https://github.com/jw-12138/r2-uploader?tab=readme-ov-file. However doing it on the frontend is a bad idea because I have to use a secret key, and if I move it to the backend that would be more work.
I found some good resources for url masking which do not actually guarantee that the video can't be downloaded but it is nice to …
=> feat: make video upload down to 5min for <500mb

apps/dashboard/src/lib/components/Course/components/NewsFeed/NewFeedModal.svelte, apps/dashboard/src/lib/components/Course/components/NewsFeed/NewsFeedCard.svelte, apps/dashboard/src/lib/utils/functions/validator.js
This PR validates the post or comment being sent in the newsfeed using zod 
Fixes #214
https://github.com/rotimi-best/classroomio/assets/69228399/194fe4f8-5d25-404b-9ab4-b7a019caa6f1
- run it on localhost
=> feat: Validate newsfeed post and comment with zod

apps/dashboard/src/lib/components/Course/components/People/InviationModal.svelte, apps/dashboard/src/lib/components/Course/components/People/InvitationModal.svelte, apps/dashboard/src/lib/components/Course/components/People/store.js, apps/dashboard/src/routes/courses/[id]/people/+page.svelte
Fixes #218 
- Go to the people page under the course route and click on "Add" then watch the url add a "?add=true" query parameter then watch the query parameter disappear when the modal closes.
=> feat: Trigger add modal in People page via url

apps/classroomio-com/package.json, apps/classroomio-com/src/lib/Navigation/Navigation.svelte, apps/classroomio-com/svelte.config.js, pnpm-lock.yaml
Fixes #199 
- Go to classroomio.com then click on "Our Superpowers", select any of the sub navs and study the scrolling.
=> fix: Melt UI bug & autoscroll bug on the landing page

apps/dashboard/src/routes/404/+page.svelte, apps/dashboard/src/routes/home/+page.server.ts
=> chore: Redirect to landing page if org not found

apps/backend/package.json, apps/backend/server.js, apps/backend/src/routes/katex.js, apps/dashboard/src/lib/components/TextEditor/index.svelte, apps/dashboard/src/lib/utils/functions/tinymce/plugins.ts, apps/dashboard/src/routes/courses/[id]/lessons/+layout.svelte, pnpm-lock.yaml
This PR adds support for math formulas in our TinyMCE editor using latex. Thanks to a plugin by codecogs.
Read more here: https://editor.codecogs.com/docs/3-Tiny_MCE_v6.php
Fixes #231
- Quick demo: https://youtu.be/FJ4Ur2Zx4XU
=> feat: add math equation support in Tinymce

apps/dashboard/src/lib/components/Course/components/Lesson/Materials/components/ComponentSlide.svelte, apps/dashboard/src/lib/components/Course/components/Lesson/Materials/index.svelte
=> feat: support canva presentation in a lesson

apps/dashboard/src/lib/components/Course/components/NewsFeed/NewsFeedCard.svelte
This PR aligns the emoji in the newsfeed
Fixes #248 
- Test A
- Test B
=> fix: Aligned newsfeed emoji

apps/classroomio-com/src/lib/Body/Body.svelte, apps/classroomio-com/src/lib/Hero/Hero.svelte, apps/classroomio-com/src/lib/Navigation/Navigation.svelte, apps/classroomio-com/src/lib/StudentDashboard/StudentDashboard.svelte, apps/classroomio-com/src/lib/Testimonial/Testimonial.svelte, apps/docs/pages/contributor-guides/student-dashboard.mdx
This adds a text animation to the hero section of the landing page.
Fixes #
- Go to classroomio.com
=> chore: landing page improvements

apps/dashboard/src/routes/org/[slug]/community/[slug]/+page.svelte
Fixes #247
- Go to the community page, click on a question then click on "edit".
=> fix: Select dropdown on Edit mode in community page changes height

apps/dashboard/src/lib/components/Course/components/Ceritficate/Design.svelte
This PR makes the text input of course description in certificate visible 
Fixes #252 
- run on localhost
=> fix: Made the text input of course description in certificate visible 

apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/MarkExerciseModal.svelte
Fixes #224 
- Grade an exercise then click on "Submit Grade
=> feat: After use clicks "Submit Grade", close the tab

apps/classroomio-com/src/lib/Hero/Hero.svelte, apps/classroomio-com/src/routes/blog/+page.svelte, apps/classroomio-com/static/hero-bg.svg
Fixes #259 
- Go to classroomio.com and click on "blog".
=> chore: Update hero section of /blog

apps/dashboard/src/lib/components/Course/components/Lesson/store/lessons.ts, apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte, apps/dashboard/src/lib/utils/functions/validator.js, apps/dashboard/src/routes/courses/[id]/+page.svelte, apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte, apps/dashboard/src/routes/courses/[id]/marks/+page.svelte
This PR fixes the empty lesson bug 
Fixes #310 
https://github.com/rotimi-best/classroomio/assets/69228399/fa4db456-c357-4e31-b3fa-0fb71a5de7be
- run on local host
=> fix: Fix empty lesson title bug

apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/EditMode.svelte, apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/ViewMode.svelte, apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/functions.js, apps/dashboard/src/lib/components/Question/CheckboxQuestion/index.svelte, apps/dashboard/src/lib/components/Question/RadioQuestion/index.svelte, apps/dashboard/src/lib/components/Question/TextareaQuestion/index.svelte, apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
This PR automatically movs to the next question when a correct otpion is selected 
Fixes #312 
- [x ] Enhancement (small improvements)
- local host
=> feat: Auto move to the next question

apps/dashboard/src/lib/components/Org/Settings/OrgSettings.svelte, apps/dashboard/src/lib/utils/functions/validator.js
Fixes #336
- Create a new account and go through the onboarding process. Try to start or end the organization name using hyphens
- Go to the settings page, try to update the organization name or domain and try using hyphens at either the start or end.
- To confirm other functionalities still work, I updated the user avatar
=> fix: Prevent hypen at start or end of organzation or domain name

apps/backend/src/utils/withEmailTemplate.js, apps/dashboard/src/lib/components/Email/EmailTemplate.svelte
Reverts rotimi-best/classroomio#353
=> Revert "feat: updated the email template"

apps/dashboard/src/lib/components/CourseLandingPage/index.svelte
=> feat(course-landing-page): redesign course content

apps/dashboard/src/lib/components/TextEditor/index.svelte
Fixes #363 
- Follow the instructions in [this video](https://www.loom.com/share/49feba88ec9c4be98bcde0526ba56013?sid=8e9b82fe-5a03-40ce-b462-1e89aca26402)
=> fix: bug on gift section of course landing page

apps/classroomio-com/src/routes/tools/pomodoro/+page.svelte
This PR stores the todo list to local storage so even after a refresh, the user still has access to the todo list he/she created.
Fixes #
- Go to the Pomodoro tool, make a todo list and hit refresh
=> feat: Store todolist to localStorage

apps/classroomio-com/src/routes/tools/progress/+page.svelte, apps/classroomio-com/src/routes/tools/progress/components/Avatar.svelte, apps/classroomio-com/src/routes/tools/progress/components/Report.svelte
This PR reorders the avatar list so it aligns with the new set of avatars.
Fixes #
- Test A
- Test B
=> feat:  Progress Report avatar update

apps/dashboard/src/lib/components/CourseContainer/index.svelte, apps/dashboard/src/lib/components/Org/Settings/TeamMembers.svelte, apps/dashboard/src/routes/onboarding/+page.svelte
1. Paid users can add more admins
2. Org admins on signup are verified by default
3. Allow admins see the content of all courses
- Test A
- Test B
=> fix: org improvements

apps/dashboard/src/routes/org/[slug]/courses/+page.svelte
This pr sets the min-width of the dropdown to align properly
Fixes #392 
https://github.com/user-attachments/assets/4734d16c-b619-449b-b7e2-c6005d0a1db6
- Test A
-go to the courses, check the dropbox
- Test B
=> fix: dropdown alignment

apps/dashboard/src/lib/components/Org/Settings/Profile.svelte, apps/dashboard/src/lib/utils/functions/validator.js, apps/dashboard/src/lib/utils/translations/en.json
Fixes #389 
- Try to update your email address on the profile page and use an incorrect email address format. You should get an error.
=> feat: add validation for updating email on profile

apps/dashboard/src/lib/components/Course/components/Lesson/Materials/index.svelte, apps/dashboard/src/lib/components/Courses/components/NewCourseModal/index.svelte
Their pr allows to perfectly align the button in text mode.
Fixes #366 
https://github.com/user-attachments/assets/4edb308a-80ea-489d-9504-9c1a5fa5d8f8
- Test A make a lesson, write the notes in the material section, click on save.
- Test B
- [] Commented on my code in hard-to-understand bits
=> fix: lesson widget alignment on page

supabase/seed.sql
Modifies seed data to reflect database changes
Fixes #382 
Student video [link](https://drive.google.com/file/d/1nKJRqMs-AwEiL5ZMHMVkF1Ivzs6Vy2Ls/view?usp=sharing)
Tutor video [link
](https://drive.google.com/file/d/1pHzH5ynr04MsqV6FK_PbVVC_qDkMv8U9/view?usp=sharing)
=> chore: modifies seed data 

apps/dashboard/src/lib/components/Courses/components/Card/index.svelte, apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte, supabase/migrations/20240717053936_rls.sql
Fixes [#70](https://github.com/rotimi-best/classroomio/issues/70)
- Make sure all functionalities are working fine as before
=> feat: RLS on all tables

apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/EditMode.svelte
=> fix(edit-mode): add style for native select css

apps/dashboard/src/lib/components/Org/Settings/Profile.svelte, apps/dashboard/src/lib/utils/functions/validator.js, apps/dashboard/src/lib/utils/translations/en.json
The pr allows the validation of username and full name correctly
Fixes #397
https://github.com/user-attachments/assets/4af21d8b-cfd4-472d-a4c5-b0b87c4c1683
- Test A
go to settings, make the username and full name as empty
- Test B
=> fix: validation of username and fullname

apps/dashboard/src/lib/components/Courses/components/Card/index.svelte, apps/dashboard/src/lib/components/Modal/index.svelte, apps/dashboard/src/lib/components/Org/Settings/store.ts, apps/dashboard/src/lib/components/Pathways/components/AddCourseModal.svelte, apps/dashboard/src/lib/components/Pathways/components/DragAndDropModal.svelte, apps/dashboard/src/lib/components/Pathways/store.ts, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/routes/pathways/[id]/courses/+page.svelte
This PR Adds the Order feature to the course modal so after the user creates the course, he/she gets to arrange the course in the order they should be followed. Lastly, This PR also adds an empty state for the courses page.
Fixes # ()
- Create a course
[https://www.loom.com/share/3ea5e2dd82a346ac80cbad5414c94d51?sid=2ad6c9cf-d4d0-4ed1-91a4-db258e67e0eb](url)
=> feat: Arrange Course Modal

apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/MarkExerciseModal.svelte, apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/functions.ts, apps/dashboard/src/routes/courses/[id]/submissions/+page.svelte
The idea of this PR is to require students to mark all correct answers in a multiple choice question before moving to the next one
=> feat: multiple choice question must all be correct before next question

apps/dashboard/src/lib/components/Course/components/Lesson/ActivateSectionsModal.svelte, apps/dashboard/src/lib/components/Course/components/Lesson/LessonList.svelte, apps/dashboard/src/lib/components/Course/components/Lesson/LessonSectionList.svelte, apps/dashboard/src/lib/components/Course/components/Navigation/index.svelte, apps/dashboard/src/lib/components/Course/store.ts, apps/dashboard/src/lib/utils/services/courses/index.ts, apps/dashboard/src/lib/utils/translations/de.json, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/lib/utils/translations/es.json, apps/dashboard/src/lib/utils/translations/fr.json, apps/dashboard/src/lib/utils/translations/hi.json, apps/dashboard/src/lib/utils/translations/pt.json, apps/dashboard/src/lib/utils/translations/ru.json, apps/dashboard/src/lib/utils/translations/vi.json, apps/dashboard/src/routes/courses/[id]/lessons/+page.svelte, apps/dashboard/src/routes/courses/[id]/lessons/[...lessonParams]/+page.svelte, supabase/migrations/20240811123634_lesson_section.sql
Fixes https://github.com/rotimi-best/classroomio/issues/430
- Test A
- Test B
=> feat: reorder sections and lessons gracefully

apps/classroomio-com/package.json, apps/classroomio-com/src/app.html, apps/classroomio-com/src/blog/google-open-source-peer-bonus.md, apps/classroomio-com/src/blog/pranav-hits-100-students.md, apps/classroomio-com/src/routes/+layout.svelte, apps/classroomio-com/src/routes/+layout.ts, apps/classroomio-com/src/routes/blog/+page.svelte, apps/classroomio-com/src/routes/blog/[slug]/+page.svelte, apps/classroomio-com/src/routes/blog/[slug]/+page.ts, apps/dashboard/package.json, apps/dashboard/src/lib/components/CourseLandingPage/constants.ts, apps/dashboard/src/routes/+layout.server.ts, apps/dashboard/src/routes/course/[slug]/+page.ts, pnpm-lock.yaml
Creates a blog post of our first customer to hit 100 students
- Test A
- Test B
=> docs: 100 students milestone

apps/dashboard/src/lib/components/Org/Pathway/api.ts, apps/dashboard/src/lib/components/Pathways/components/Certificate/StudentCertificate/Index.svelte, apps/dashboard/src/lib/components/Pathways/components/Certificate/StudentCertificate/UnlockedCertificate.svelte, apps/dashboard/src/lib/utils/functions/pathway.ts, apps/dashboard/src/lib/utils/services/pathways/index.ts, apps/dashboard/src/routes/lms/+page.svelte, apps/dashboard/src/routes/lms/mylearning/+page.svelte, apps/dashboard/src/routes/pathways/[id]/settings/+page.svelte
=> fix: worked on the settings 

apps/dashboard/src/lib/components/Course/components/People/BatchSettingsModal.svelte, apps/dashboard/src/lib/components/Course/components/People/CreateBatchModal.svelte, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/routes/courses/[id]/people/+page.svelte, apps/dashboard/src/routes/courses/[id]/people/+page.ts, apps/dashboard/src/routes/courses/[id]/people/[...batchParams]/+page.js, apps/dashboard/src/routes/courses/[id]/people/[...batchParams]/+page.svelte
=> feat: course batch UI

apps/dashboard/src/lib/components/Org/Settings/Domains.svelte
=> chore: disable custom domain on free

apps/dashboard/src/lib/components/CourseLandingPage/components/SectionsDisplay.svelte, apps/dashboard/src/lib/components/CourseLandingPage/index.svelte, apps/dashboard/src/lib/utils/services/courses/index.ts, apps/dashboard/src/lib/utils/translations/de.json, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/lib/utils/translations/es.json, apps/dashboard/src/lib/utils/translations/fr.json, apps/dashboard/src/lib/utils/translations/hi.json, apps/dashboard/src/lib/utils/translations/pt.json, apps/dashboard/src/lib/utils/translations/ru.json, apps/dashboard/src/lib/utils/translations/vi.json, apps/dashboard/src/routes/courses/[id]/landingpage/+page.svelte
This PR updates course landing page with sections
Fixes #455 
- Navigate to a course then the landing page and scroll down.
=> feat: Update course landing page with sections

apps/dashboard/src/lib/components/Course/components/NewsFeed/NewsFeedCard.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/CertificateForm.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/GoalsForm.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/InstructorForm.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/RequirementForm.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/Editor/index.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/PricingSection.svelte, apps/dashboard/src/lib/components/CourseLandingPage/components/SectionsDisplay.svelte, apps/dashboard/src/lib/components/CourseLandingPage/constants.ts, apps/dashboard/src/lib/components/CourseLandingPage/index.svelte, apps/dashboard/src/lib/components/CourseLandingPage/utils.ts, apps/dashboard/src/lib/components/Courses/components/Card/index.svelte, apps/dashboard/src/lib/components/Org/LandingPage/index.svelte, apps/dashboard/src/lib/components/UploadImage/index.svelte, apps/dashboard/src/lib/utils/functions/course.ts, apps/dashboard/src/lib/utils/store/org.ts, apps/dashboard/src/lib/utils/translations/de.json, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/lib/utils/translations/es.json, apps/dashboard/src/lib/utils/translations/fr.json, apps/dashboard/src/lib/utils/translations/pt.json, apps/dashboard/src/lib/utils/translations/ru.json, apps/dashboard/src/lib/utils/translations/vi.json, apps/dashboard/src/lib/utils/types/index.ts, apps/dashboard/src/routes/+layout.svelte, supabase/migrations/20240907090948_open_orgplan_for_landingpage.sql
- Customize certificate section in the course landing page
- Make gift section html rendered
- Hide classroomio powered by on org landing page for paid customers
- Show discount on course cards
=> fix: course and org landing page improvements

apps/dashboard/src/lib/components/Courses/components/Card/index.svelte, apps/dashboard/src/lib/components/Courses/components/List/index.svelte, apps/dashboard/src/lib/components/Courses/index.svelte, apps/dashboard/src/lib/components/Org/Pathway/api.ts, apps/dashboard/src/lib/utils/functions/pathway.ts, apps/dashboard/src/lib/utils/services/courses/index.ts, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/routes/lms/explore/+page.svelte, apps/dashboard/src/routes/lms/mylearning/+page.svelte, supabase/migrations/20240829203438_explore_courses.sql
This PR adds the pathway course to the explore page of the LMS
- Test A
- Test B
=> feat: finished the explore courses of the LMS page

apps/dashboard/src/routes/lms/exercises/+page.svelte
This PR Fixes the Error 500 that shows up on prod whenever users refresh /lml/exercises page.
- Test A
- Test B
=> fix: error 500 for /lms/exercise

apps/classroomio-com/src/app.html, apps/classroomio-com/src/routes/+layout.svelte, apps/dashboard/src/app.html, apps/dashboard/src/routes/+layout.svelte
Fixes #493
- Check Umami Dashboard if localhost interactions on Landing page and dashboard are being recorded.
=> feat: disable umami analytics on localhost for dashboard and classroomio-com

apps/classroomio-com/src/lib/Home/MoreFeatures.svelte
This PR fixes the free tools section on the home page of the landing page
- Test A
- Test B
=> fix: restructure free tools section on landing page

apps/dashboard/src/lib/utils/store/user.ts
Fixes #466 
Before:
After:
- Go to profile settings page and refresh, there should be no sudden image flashes.
=> feat: fix flashing avatar

.vscode/settings.json, apps/dashboard/src/lib/components/AuthUI/index.svelte, apps/dashboard/src/lib/components/Org/LandingPage/index.svelte, apps/dashboard/src/lib/components/Org/VerifyEmail/VerifyEmailModal.svelte, apps/dashboard/src/lib/utils/functions/appSetup.ts, apps/dashboard/src/lib/utils/functions/translations.ts, apps/dashboard/src/lib/utils/functions/validator.ts, apps/dashboard/src/lib/utils/services/courses/index.ts, apps/dashboard/src/lib/utils/services/org/index.ts, apps/dashboard/src/lib/utils/translations/de.json, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/lib/utils/translations/es.json, apps/dashboard/src/lib/utils/translations/fr.json, apps/dashboard/src/lib/utils/translations/hi.json, apps/dashboard/src/lib/utils/translations/pt.json, apps/dashboard/src/lib/utils/translations/ru.json, apps/dashboard/src/lib/utils/translations/vi.json, apps/dashboard/src/routes/+layout.server.ts, apps/dashboard/src/routes/+layout.svelte, apps/dashboard/src/routes/+layout.ts, apps/dashboard/src/routes/invite/t/[hash]/+page.svelte, apps/dashboard/src/routes/login/+page.svelte, apps/dashboard/src/routes/org/[slug]/setup/+page.ts, apps/dashboard/src/routes/signup/+page.svelte
=> feat: automatically detect language on server and translate UI

apps/classroomio-com/src/lib/Navigation/Navigation.svelte, apps/classroomio-com/src/routes/+layout.server.ts, apps/classroomio-com/src/routes/+layout.svelte, apps/classroomio-com/src/routes/+layout.ts, package.json
=> feat: add github stars

apps/course-app/svelte.config.js, apps/dashboard/src/lib/components/Course/components/Lesson/Exercise/DeleteConfirmation.svelte, apps/dashboard/src/lib/components/Course/components/People/DeleteConfirmation.svelte, apps/dashboard/src/lib/components/Org/Community/DeleteModal.svelte, apps/dashboard/src/routes/org/[slug]/community/[slug]/+page.svelte, apps/dashboard/src/routes/org/[slug]/community/ask/+page.svelte
=> fix: show validation message in community ask page

apps/dashboard/src/lib/components/Course/components/Settings/index.svelte, apps/dashboard/src/lib/components/Org/Settings/LandingpageSettings.svelte, apps/dashboard/src/lib/components/Org/Settings/OrgSettings.svelte, apps/dashboard/src/lib/components/Org/Settings/Profile.svelte, apps/dashboard/src/lib/components/UnsavedChanges/index.svelte, apps/dashboard/src/lib/components/UploadImage/index.svelte, apps/dashboard/src/lib/utils/translations/de.json, apps/dashboard/src/lib/utils/translations/en.json, apps/dashboard/src/lib/utils/translations/es.json, apps/dashboard/src/lib/utils/translations/fr.json, apps/dashboard/src/lib/utils/translations/hi.json, apps/dashboard/src/lib/utils/translations/pt.json, apps/dashboard/src/lib/utils/translations/ru.json, apps/dashboard/src/lib/utils/translations/vi.json
This PR trigger the confirm warning for unsaved changes, it blocks navigation until an action is confirmed by the user. This changes were added to the
1) landingpage settings
2) profile settings
3) organization settings
Fixes #488 
https://github.com/user-attachments/assets/94a2b82b-b3f5-459e-b9d0-1e2785e70a49
- Start the dev server and navigate to the settings page
- make a change and try navigating to another page without saving
=> feat: Trigger confirm warning for unsaved changes 
